// toad_modules/ionic-angular/es2015/components/note/note.js
import { Directive, ElementRef, Renderer } from '@angular/core';
import { Config } from '../../config/config';
import { Ion } from '../ion';
/**
 * \@name Note
 * \@module ionic
 * \@description
 * A note is detailed item in an ion-item. It creates greyed out element that can be on the left or right side of an item.
 * \@usage
 *
 * ```html
 * <ion-content>
 *   <ion-list>
 *     <ion-item>
 *       <ion-note item-left>
 *         Left Note
 *       </ion-note>
 *       My Item
 *       <ion-note item-right>
 *         Right Note
 *       </ion-note>
 *     </ion-item>
 *   </ion-list>
 * </ion-content>
 * ```
 * {\@link /docs/api/components/api/components/item/item ion-item}
 */
export class Note extends Ion {
    /**
     * @param {?} config
     * @param {?} elementRef
     * @param {?} renderer
     */
    constructor(config, elementRef, renderer) {
        super(config, elementRef, renderer, 'note');
    }
}
Note.decorators = [
    { type: Directive, args: [{
                selector: 'ion-note'
            },] },
];
/**
 * @nocollapse
 */
Note.ctorParameters = () => [
    { type: Config, },
    { type: ElementRef, },
    { type: Renderer, },
];
function Note_tsickle_Closure_declarations() {
    /** @type {?} */
    Note.decorators;
    /**
     * @nocollapse
     * @type {?}
     */
    Note.ctorParameters;
}
//# sourceMappingURL=note.js.map

// src/components/note/note.tsx
import { Component, h } from '../index';


/**
  * @name Note
  * @module ionic
  * @description
  * A note is detailed item in an ion-item. It creates greyed out element that can be on
  * the left or right side of an item.
  *
  * @usage
  *
  * ```html
  * <ion-content>
  *   <ion-list>
  *     <ion-item>
  *       <ion-note slot="start">
  *         Left Note
  *       </ion-note>
  *       My Item
  *       <ion-note slot="end">
  *         Right Note
  *       </ion-note>
  *     </ion-item>
  *   </ion-list>
  * </ion-content>
  * ```
  *
  * {@link /docs/api/components/api/components/item/item ion-item}
  */
@Component({
  tag: 'ion-note',
  styleUrls: {
    ios: 'note.ios.scss',
    md: 'note.md.scss',
    wp: 'note.wp.scss'
  },
  host: {
    theme: 'note'
  }
})
export class Note {
  render() {
    return <slot></slot>;
  }
}
